### ISSUE TITLE
Allow to include resources/file uploads in CfP

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#1316]

**Comment by twopercentjazz** [comment]
I'm working on this.

**Comment by 1jc** [comment]
I am working with @twopercentjazz on this issue

**Comment by ProfessorCattington** [comment]
I will help on this issue as well

**Comment by 1jc** [comment]
1jc  Joette Damo researched this #1316 which should be **closed**    **closed**    due to the following circumstances

**commit   f81e158**      https://github.com/pretalx/pretalx/commit/f81e158980af27fbb513461df4bce0ae844fea7a "Warn client side on too large file uploads"     was completed

to satisfy Issue #1329 Frontend should block large file uploads with a warning - **this issue is closed**

to satisfy issue #1084 Show avatar image upload size limit in help text - **This issue is closed** and issue #1084 duplicate of issue #1120 Profile image upload can trigger 413 "request entity too big" from OpenResty - **This issue is closed.**

**commit   f81e158**    clearly satisfies  and issue #1316 should be closed        

please review @ProfessorCattington @twopercentjazz @derrekdo

**Comment by rixx** [comment]
I'm not sure what's going on here, but f81e158 has no bearing on this issue. Please either:

- work on this issue
- ask clarifying questions if you're unclear on what to work on
- don't post noisy comments like the one above

**Comment by 1jc** [comment]
@twopercentjazz @ProfessorCattington @1jc #1633 now closed by commit abcbebc 2 weeks ago by rixx and he states resources are not part of review - other part of issue should be resolved via #1316   

written by 1jc

**Comment by rixx** [comment]
I'm still not sure what's going on here, but I am going to ask you again to either work on this issue or ask clarifying questions. Commenting on issue 1316 that it should be resolved via that same issue 1316 isn't helpful.

Last warning.

**Comment by 1jc** [comment]
@rixx what part of issue #1316 should be resolved unsure please clarify appreciate your help       1jc
