### ISSUE TITLE
'Santize markdown preview' commit introduces rebuild error

### ISSUE THREAD

**Issue by yvovandoorn** [pretalx/pretalx#1811]
### Problem and impact

With https://github.com/pretalx/pretalx/commit/58e9990d4e2c81d1eb9a23f77801efcf5155ac08, a new file, `src/pretalx/static/vendored/purify.min.js` was added. However the rebuild command and/or binaries are not seeing it:

```
ERROR 2024-08-05 22:32:23,879 django.request log Internal Server Error: XXXXXX
Traceback (most recent call last):
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/templatetags/static.py", line 116, in render
    url = self.url(context)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/templatetags/static.py", line 113, in url
    return self.handle_simple(path)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/templatetags/static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "/app/pretalx/.local/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'vendored/purify.min.js'
```

Reverting to a prior commit prior to https://github.com/pretalx/pretalx/commit/58e9990d4e2c81d1eb9a23f77801efcf5155ac08 makes the problem disappear. 

### Steps to reproduce

1.
2.
3.
4.

**Comment by rixx** [comment]
Resolved in 520823ebc.

Please note that the main branch of pretalx is ***NOT*** meant to be deployed blindly. We make no guarantees that the main branch of pretalx will always be deploy-ready. Please don't open bugs for issues that may just be halted mid-development.

**Comment by rixx** [comment]
Sounds like you didn't restart your server process after the rebuild command.

Two notes:

1. Please don't open bug reports for deployment issues. You can either take deployment problems to GitHub discussions, where the community may find the time to help, or help us maintain this project by paying for pretalx support.
2. Please note that we make ***absolutely no promises*** that the main branch of pretalx is deployment ready. Even if the file was missing from pretalx (which it isn't!), that could just have been because the feature was mid-development.

**Comment by yvovandoorn** [comment]
Hi @rixx apologies. However I should add that I absolutely restarted the server processes multiple times -- including rebooting the server twice. Problem persisted. Thats why I ultimately opened up this report.

**Comment by rixx** [comment]
@yvovandoorn The error indicates that you either did not run `rebuild` or didn't restart the server. There's no other reason why the staticfiles manifest and the served static files would diverge. Now that I look at the error again, it actually indicates that you didn't run `rebuild`, but did restart the server, as pretalx is trying to serve a file that was not built.
