### ISSUE TITLE
Event time in HTML export Tooltip and Details wrong but timeline correct.

### ISSUE THREAD

**Issue by oe1rfc** [pretalx/pretalx#500]
## Expected Behavior
Event time in tooltip and events details view should display the correct event time.

## Current Behavior
Overview tooltip shows several hours time difference (10:00 vs 17:00) to timeline in same page:
![export overview](https://user-images.githubusercontent.com/892336/45377936-6115ba00-b5fc-11e8-92b9-13d1dda6b911.jpg)

Event details also has wrong time:
![export details](https://user-images.githubusercontent.com/892336/45377947-64a94100-b5fc-11e8-8ff5-8037dd2338b7.jpg)

Event is scheduled in the editor at 17:00:
![schedule editor](https://user-images.githubusercontent.com/892336/45377912-522f0780-b5fc-11e8-84c6-28d282fbc296.jpg)

In the schedule.xml export the same event has a date value of _"2018-10-22T10:00:00-05:00"_, which would be the correct time in a wrong time zone.

## Steps to Reproduce
example instance at https://fahrplan.privacyweek.at/

## Your Environment

* Version used: 0.7.1

**Comment by oe1rfc** [comment]
update: The same view is correct in the non-export schedule preview (/<conference>/schedule/v/wip/).

**Comment by luto** [comment]
adding

```
from django.utils import timezone
timezone.activate(event.timezone)
```

to the `export_schedule_html` management command resolves this, but I am not sure, if that's the right way to tackle it.

@rixx any opinions?

I will apply the quick-fix manually for PW18, so there is no rush for this specific case.

**Comment by rixx** [comment]
I think you'll want to use ``with django.utils.timezone.override(tz)`` to make sure you don't have unexpected side effects.

**Comment by rixx** [comment]
Fix has been pushed – please re-open the issue if the fix is not sufficient.

**Comment by luto** [comment]
ah, thanks! :) I didn't get it to work yet, because the export still crashes under 3.8 :/ will investigate further.
